definitions:
  club.CreateResponse:
    properties:
      msg:
        description: 返回的信息
        type: string
    type: object
  club.ResLogin:
    properties:
      msg:
        description: 信息
        type: string
      token:
        description: token
        type: string
    type: object
  club.ResUrl:
    properties:
      callback_str:
        description: 回调的字符串
        type: string
      url:
        description: 签名url
        type: string
    type: object
  club.Response:
    properties:
      msg:
        description: 返回的信息
        type: string
    type: object
  club.RspRegister:
    properties:
      club_id:
        description: 社团Id
        type: integer
      club_name:
        type: string
      msg:
        description: 信息
        type: string
      password:
        description: 用户密码
        type: string
    type: object
  user.ResponseClubInfo:
    properties:
      avatar_addr:
        description: 社团头像url地址
        type: string
      club_name:
        description: 社团名称
        type: string
      created_at:
        type: string
      id:
        type: integer
      introduction:
        description: 社团简介
        type: string
      num_of_fans:
        description: 粉丝数
        type: integer
      num_of_favorites:
        description: 活动被收藏的总次数
        type: integer
    type: object
  user.ResponsePost:
    properties:
      article:
        description: 标题
        type: string
      avatar_addr:
        description: 头像url地址
        type: string
      club_id:
        description: 社团Id
        type: integer
      club_name:
        description: 社团名称
        type: string
      content:
        description: 内容
        type: string
      created_at:
        description: 创建时间
        type: string
      id:
        description: Msg         string `json:"msg"`   //信息 如"获取成功"
        type: integer
      is_notice:
        description: 是否为通知
        type: boolean
      picture_addr:
        description: 帖子图片的多个可访问地址
        items:
          type: string
        type: array
      updated_at:
        description: 更新时间(刚创建时为空)
        type: string
    type: object
  user.ResponsePosts:
    properties:
      data:
        description: data内包涵多条帖子数据
        items:
          $ref: '#/definitions/user.ResponsePost'
        type: array
    type: object
  user.ResponseSubscribe:
    properties:
      msg:
        description: 信息
        type: string
    type: object
info:
  contact: {}
paths:
  /club/introduction:
    put:
      parameters:
      - description: Bearer 用户令牌 例:Bearer fbhraewifvg43uwerfaewobf
        in: header
        name: Authorization
        required: true
        type: string
      - description: 社团简介
        in: formData
        name: introduction
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/club.Response'
      summary: 修改社团简介
  /club/post:
    post:
      parameters:
      - description: Bearer 用户令牌 例:Bearer fbhraewifvg43uwerfaewobf
        in: header
        name: Authorization
        required: true
        type: string
      - description: 标题,min=2
        in: formData
        minLength: 2
        name: article
        required: true
        type: string
      - description: 内容,min=10
        in: formData
        minLength: 10
        name: content
        required: true
        type: string
      - description: 是否为通知
        in: formData
        name: is_notice
        type: boolean
      - description: 包涵要上传的帖子图片的id的数组,最多9张图
        in: formData
        items:
          type: integer
        maxItems: 9
        name: picture_ids
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/club.CreateResponse'
      summary: 创建活动或动态
  /club/signed_url:
    get:
      description: 获取上传图片的url及回调字符串,图片Id
      parameters:
      - description: Bearer 用户令牌 例:Bearer fbhraewifvg43uwerfaewobf
        in: header
        name: Authorization
        type: string
      - description: 要发送的图片名
        in: query
        name: picture_name
        required: true
        type: string
      - description: '"post_picture"或"avatar"'
        in: query
        name: type
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/club.ResUrl'
      summary: 获取上传图片或头像的签名
  /login:
    post:
      parameters:
      - description: 社团名或社团账号,至少2位
        in: formData
        minLength: 2
        name: club_name_or_id
        required: true
        type: string
      - description: 密码,至少6位
        in: formData
        minLength: 6
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/club.ResLogin'
      summary: 登录社团账号
  /register:
    post:
      parameters:
      - description: 社团登录账号7-12位
        in: formData
        maximum: 999999999999
        minimum: 99999
        name: club_id
        required: true
        type: integer
      - description: 社团名称
        in: formData
        minLength: 2
        name: club_name
        required: true
        type: string
      - description: 邀请码
        in: formData
        name: invitation_code
        required: true
        type: integer
      - description: 密码6-32位
        in: formData
        maxLength: 32
        minLength: 6
        name: password
        required: true
        type: string
      - description: 确认密码
        in: formData
        name: password2
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/club.RspRegister'
      summary: 注册社团账号
  /user/club_info:
    get:
      parameters:
      - description: 社团id
        in: query
        name: club_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseClubInfo'
      summary: 查看社团信息,可用于展示社团的页面
  /user/post:
    get:
      parameters:
      - description: 帖子的id,min=1
        in: query
        name: post_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponsePost'
      summary: 获取单条通知/动态(详情)
  /user/posts:
    get:
      parameters:
      - description: '"要查询的是否为通知,是则为true,否则为false"'
        in: query
        name: is_notice
        type: boolean
      - description: 页码,最小为1
        example: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - description: 每页数据量,最大为40
        example: 10
        in: query
        maximum: 40
        minimum: 1
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: data内有多条post
          schema:
            $ref: '#/definitions/user.ResponsePosts'
      summary: 获取最新的多条通知/动态
  /user/posts_from_clubs_user_fellow:
    get:
      parameters:
      - description: 页码,最小为1
        example: 1
        in: query
        minimum: 1
        name: page
        required: true
        type: integer
      - description: 每页数据量,最大为40
        example: 10
        in: query
        maximum: 40
        minimum: 1
        name: size
        required: true
        type: integer
      - in: query
        name: student_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: data内有多条post
          schema:
            $ref: '#/definitions/user.ResponsePosts'
      summary: 获取用户关注的社团发布的最新的多条通知和动态
  /user/subscribe:
    delete:
      parameters:
      - description: 社团Id
        in: query
        name: club_id
        required: true
        type: integer
      - description: 学号
        in: query
        name: student_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseSubscribe'
      summary: 取消关注社团
    post:
      parameters:
      - description: 社团Id
        in: query
        name: club_id
        required: true
        type: integer
      - description: 学号
        in: query
        name: student_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.ResponseSubscribe'
      summary: 关注社团
swagger: "2.0"
